language: python
osx_image: xcode13.1

env:
  global:
    - PATH=$HOME/.cargo/bin:$PATH
    - CC="clang"
    - CFLAGS="-O2 -fno-plt -flto=thin"
    - LDFLAGS="-O2 -flto=thin -fuse-ld=lld -Wl,--as-needed"
    - RUSTFLAGS="-C linker=clang"
    - CARGO_UNSTABLE_SPARSE_REGISTRY="true"

matrix:
  include:
    - name: "Build and Test"
      env: TOOLCHAIN=nightly-2022-11-20
        INTERPRETER=python3

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain $TOOLCHAIN --profile minimal -y
  - rustup component add rust-src --toolchain $TOOLCHAIN-x86_64-apple-darwin
  - rustup target add aarch64-apple-darwin
  - pip install --index-url 'https://:2022-12-02T15:31:00.217647Z@time-machines-pypi.sealsecurity.io/' --upgrade pip "maturin>=0.14,<0.15" wheel
  - pip install --index-url 'https://:2022-12-02T15:31:00.217647Z@time-machines-pypi.sealsecurity.io/' -r test/requirements.txt -r integration/requirements.txt

script:
  - rustup default $TOOLCHAIN
  - maturin build --release --strip --features=unstable-simd,yyjson --interpreter $INTERPRETER -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target=x86_64-apple-darwin
  - pip install --index-url 'https://:2022-12-02T15:31:00.217647Z@time-machines-pypi.sealsecurity.io/' target/wheels/orjson*.whl
  - pytest -s -rxX -v test
  - ./integration/run thread
  - ./integration/run http

  # Build universal2
  - PYO3_CROSS_LIB_DIR=$(python -c "import sysconfig;print(sysconfig.get_config_var('LIBDIR'))") maturin build --release --strip --features=unstable-simd,yyjson --interpreter $INTERPRETER --universal2
  - pip install --index-url 'https://:2022-12-02T15:31:00.217647Z@time-machines-pypi.sealsecurity.io/' --force-reinstall target/wheels/orjson*universal2.whl
  - pytest -s -rxX -v test

after_success:
  - ./ci/deploy target/wheels/*_x86_64.whl
  - ./ci/deploy target/wheels/*_universal2.whl
