variables:
  toolchain: nightly-2022-11-20

jobs:

- job: macos_python311_amd64
  pool:
    vmImage: macOS-13
  variables:
    interpreter: python3.11
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11.0'
      addToPath: true
      allowUnstable: true
  - checkout: self
  - template: ./azure-macos.yml

- job: macos_python310_amd64
  pool:
    vmImage: macOS-13
  variables:
    interpreter: python3.10
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml

- job: macos_python39_amd64
  pool:
    vmImage: macOS-13
  variables:
    interpreter: python3.9
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml

- job: macos_python38_amd64
  pool:
    vmImage: macOS-13
  variables:
    interpreter: python3.8
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml

- job: macos_python37_amd64
  pool:
    vmImage: macOS-13
  variables:
    interpreter: python3.7
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      addToPath: true
  - checkout: self
  - template: ./azure-macos.yml

- job: win_python311_amd64
  pool:
    vmImage: windows-2022
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.11.0\x64\python.exe
    target: x86_64-pc-windows-msvc
    uniqueinput: a
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11.0'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python310_amd64
  pool:
    vmImage: windows-2022
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.10.8\x64\python.exe
    target: x86_64-pc-windows-msvc
    uniqueinput: b
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10.8'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python39_amd64
  pool:
    vmImage: windows-2022
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.9.13\x64\python.exe
    target: x86_64-pc-windows-msvc
    uniqueinput: c
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.9.13'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python38_amd64
  pool:
    vmImage: windows-2022
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.8.10\x64\python.exe
    target: x86_64-pc-windows-msvc
    uniqueinput: d
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.8.10'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml

- job: win_python37_amd64
  pool:
    vmImage: windows-2022
  variables:
    interpreter: C:\hostedtoolcache\windows\Python\3.7.9\x64\python.exe
    target: x86_64-pc-windows-msvc
    uniqueinput: e
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7.9'
      addToPath: true
      architecture: 'x64'
  - checkout: self
  - template: ./azure-win.yml
