name: manylinux2014
on:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  manylinux2014:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        python: [
          { version: '3.7', abi: 'cp37-cp37m' },
          { version: '3.8', abi: 'cp38-cp38' },
          { version: '3.9', abi: 'cp39-cp39' },
          { version: '3.10', abi: 'cp310-cp310' },
          { version: '3.11', abi: 'cp311-cp311' },
        ]
    env:
      PATH: /github/home/.local/bin:/github/home/.cargo/bin:/opt/python/${{ matrix.python.abi }}/bin:/opt/rh/devtoolset-10/root/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      CC: "gcc"
      CFLAGS: "-O2 -fno-plt -flto"
      LDFLAGS: "-O2 -flto -Wl,--as-needed"
      CARGO_UNSTABLE_SPARSE_REGISTRY: "true"
    steps:
    - uses: actions/checkout@v2
    - name: Setup container
      id: start-container
      run: |
          container_id=$(docker run -e PATH -e CC -e CFLAGS -e LDFLAGS -e CARGO_UNSTABLE_SPARSE_REGISTRY -d --platform linux/amd64 -v ${PWD}:/seal -w /seal quay.io/pypa/manylinux2014_x86_64:2022-11-28-5d13db4 tail -f /dev/null)
          echo "container_id=$container_id" >> $GITHUB_OUTPUT
    - run: docker exec ${{ steps.start-container.outputs.container_id }} curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain nightly-2022-11-20 --profile minimal -y
    - run: docker exec ${{ steps.start-container.outputs.container_id }} python3 -m pip install --index-url 'https://:2022-12-02T15:31:00.217647Z@time-machines-pypi.sealsecurity.io/' --user --upgrade pip "maturin>=0.14,<0.15" wheel && maturin build --release --strip --features=unstable-simd,yyjson --compatibility manylinux2014 --interpreter python${{ matrix.python.version }}
    - run: docker exec ${{ steps.start-container.outputs.container_id }} python3 -m pip install --index-url 'https://:2022-12-02T15:31:00.217647Z@time-machines-pypi.sealsecurity.io/' --user target/wheels/orjson*.whl
    - run: docker exec ${{ steps.start-container.outputs.container_id }} python3 -m pip install --index-url 'https://:2022-12-02T15:31:00.217647Z@time-machines-pypi.sealsecurity.io/' --user -r test/requirements.txt -r integration/requirements.txt
    - run: docker exec ${{ steps.start-container.outputs.container_id }} pytest -s -rxX -v test
    - run: docker exec ${{ steps.start-container.outputs.container_id }} ./integration/run thread
    - run: docker exec ${{ steps.start-container.outputs.container_id }} ./integration/run http
    - uses: actions/upload-artifact@v4
      with:
        name: wheels_${{ matrix.python.version }}_${{ matrix.python.abi }}
        path: target/wheels
